stages:
- stage: Start_VM
  jobs:
  - job: Start_VM
    pool:
      name: DEVDEMO1US1
    steps:
    - task: vfabing.AzureVirtualMachineManagerTask.custom-build-release-task.AzureVirtualMachineManagerTask@1
      displayName: 'Start Docker Build VM'
      inputs:
        azureSubscription: $(azure.subscription)
        ResourceGroupName: docker
        VmName: $(docker.build.vm.name)
- stage: Build_Images
  jobs:
  - job: Build_Images
    displayName: 'Build Base Images'
    dependsOn: Start_VM
    pool:
      name: Docker
    variables:
      registry.password: $(sitecore.acr.password)
      sitecore.username: $(sitecore.username)
    steps:
    - powershell: |
        $(sitecore.democontainer.password) | docker login -u "sitecoredemocontainers" --password-stdin sitecoredemocontainers.azurecr.io 
        $modulePath = (Join-Path "$(Build.SourcesDirectory)" "modules")
        Import-Module (Join-Path $modulePath "SitecoreImageBuilder") -Force
        SitecoreImageBuilder\Invoke-PackageRestore  -Path (Join-Path "$(Build.SourcesDirectory)" "images") -Destination $(install.source.path) -Tags $(image.tags) -SitecoreUsername $(sitecore.username) -SitecorePassword $(sitecore.password)
        SitecoreImageBuilder\Invoke-Build -Path (Join-Path "$(Build.SourcesDirectory)" "images") -InstallSourcePath $(install.source.path) -Registry $(container.registry.name)     -Tags $(image.tags) -PushMode "WhenChanged"
      errorActionPreference: silentlyContinue
      continueOnError: "true"
      timeoutInMinutes: 240