stages:
  - stage: Build_Experimental_Images
    dependsOn: Start_VM
    jobs:
      - job: Build_Experimental_Images
        timeoutInMinutes: 720
        displayName: "Build Experimental Images"
        pool:
          name: Docker
        steps:
          - task: Docker@2
            displayName: login
            inputs:
              containerRegistry: "docker-registry"
              command: login
          - powershell: |
              $(sitecore.democontainer.password) | docker login -u "sitecoredemocontainers" --password-stdin sitecoredemocontainers.azurecr.io 
              $modulePath = (Join-Path "$(Build.SourcesDirectory)" "modules")
              Import-Module (Join-Path $modulePath "SitecoreImageBuilder") -Force
              SitecoreImageBuilder\Invoke-PackageRestore -Path (Join-Path "$(Build.SourcesDirectory)" "experimental") -Destination $(install.source.path) -Tags $(image.tags) -SitecoreUsername $(sitecore.username) -SitecorePassword $(sitecore.password)
              SitecoreImageBuilder\Invoke-Build -Path (Join-Path "$(Build.SourcesDirectory)" "experimental") -InstallSourcePath $(install.source.path) -Registry $(container.registry.name) -Tags $(image.tags)
            errorActionPreference: silentlyContinue
            continueOnError: "true"
        